---
# tasks file for oracle-java

- include: main-debian-source.yml
  when: ansible_distribution == 'Debian'
        and ansible_distribution_major_version == '8'
        and oracle_java_from_src == true

- include: main-debian-apt.yml
  when: ansible_distribution == 'Debian'
        and ansible_distribution_major_version == '8'
        and oracle_java_from_src == false